name: Featured Banner Request
title: "[Featured Banner]"
labels: featured-banner
assignees:
  - RubenSmn

body:
  - type: markdown
    attributes:
      value: |
        ## :heart: Thank you for using the Spotify Banner Creator tool!

  - type: input
    id: name
    attributes:
      label: Name (Optional)
      description: If you whish to show your name on the featured page.
    validations:
      required: false

  - type: input
    id: share_url
    attributes:
      label: Share URL
      description: Please provide the URL of the shared banner you created, [a guide](https://support.spotify.com/us/article/share-from-spotify/) if needed.
    validations:
      required: true

  - type: input
    id: playlist_url
    attributes:
      label: Spotify Playlist URL (Optional)
      description: If applicable, please provide the URL of the Spotify playlist associated with the banner.
      placeholder: "e.g., https://open.spotify.com/playlist/your_playlist_id"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thank you for your feature request!
